### ISSUE TITLE
Create Tagged Version to be compatible with Brownie

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/usingtellor#27]
This issue is about making UsingTellor compatible with [Brownie](https://eth-brownie.readthedocs.io/en/stable/index.html):

Instructions for how Brownie loads packages from Github: https://eth-brownie.readthedocs.io/en/stable/package-manager.html#installing-from-github

Looks like you can just add a tagged version on this and it'll work

**Comment by JGcarv** [comment]
Done!
