### ISSUE TITLE
add getMultipleValuesBefore

### ISSUE THREAD

**Issue by themandalore** [tellor-io/usingtellor#73]
have a way to get multipleValuesBefore

This is for a medianizer (or if someone wanted to require more stakes).  You could just get the last 5 values, require all of them are within a day old and you know that the submission is likely more secure.  

The other question is should we add a split?  Meaning you want the last 5 values that are all 1 day old.  That way you'd have to break tellor for 5 days.  ....is this wanted?

**Comment by tkernell** [comment]
https://github.com/tellor-io/usingtellor/pull/80

- this does not include a split
